### ISSUE TITLE
Document architecture 

### ISSUE THREAD

**Issue by PPACI** [cheaty-sheet/Cheaty#1]
Global architecture should be documented. 
Documentation should be added as a markdown to this ticket.

**Comment by PPACI** [comment]
# Cheaty architecture

The main goal for Cheaty is to generate html cheat sheet from an object. This objective is quite simple but it will serve as a platform for later introduced features. The code engine of Cheaty should be flexible, but keep in one place to ease future development. I propose the introduction of typescript as it will permit a greater scalability in term of code base while permitting the use of the whole Js ecosystem.

Core of Cheaty would be a class representing a cheat sheet, and method to generate html document. The first goal is too introduced a programmatic API to cheat sheet generation.

Multiple module should then be developed before the first public release :
**Yaml parsing**. Instead of creating the CS object by hand, we should be able to parse a YAML file.
**Pdf rendering**. CS object should also offer a method to render the cheat sheet as PDF on disk. This could be based on the html rendering and just be a wrapper over Puppetter to render html as pdf.

As this moment, we should have a solution to write YAML and a simple script to generate cheat sheet. But we could improve this with other features before release.

**Themes**. Use should be permitted to select different styling. Those styling are basically CSS sheet injected in the header of the html document.
**Layout**. As with themes, we should be able to select différents layout to fit different use cases.

Options will be offered in YAML and in the API to select various themes and layout.

Once everything is done, we will have to create a **cli** wrapper to permit people to only use the YAML as the main entry point and it should be ok for the first release. Then, our main objective would be to create tons of layout and css.

**Comment by Nakasar** [comment]
An example of a simple cheatsheet (for reference):

![An example](https://pbs.twimg.com/media/DxwcGinXQAEA6RV?format=jpg&name=4096x4096)
