### ISSUE TITLE
Create the core engine

### ISSUE THREAD

**Issue by PPACI** [cheaty-sheet/Cheaty#2]
Create the core engine to render a cheat sheet class as html.
More information available on #1.

**Comment by Nakasar** [comment]
Suggestion of implementation and demo in https://github.com/cheaty-sheet/Cheaty/tree/feature/html-renderer

CheatSheet has a `.render(renderType | renderer)` method (allowing for third-party renderer or other output formats).
HTML renderer renders each CheatSheet block in HTML (non-optimal process, forEach could be smarter than maps).

Edit & Run 'test/index.js' after 'npm install'.

**Comment by Nakasar** [comment]
Same in typescript:
https://github.com/cheaty-sheet/Cheaty/tree/feature/typescript-structure
